package com.tntmodders.project_404.core;

import com.tntmodders.project_404.TNT404Core;
import net.minecraftforge.fml.common.ModMetadata;

public class TNT404ModInfoCore {

    public static void load(ModMetadata meta) {
        meta.modId = TNT404Core.MODID;
        meta.name = TNT404Core.MODID;
        meta.description = "";
        meta.version = TNT404Core.VERSION;
        meta.credits = "";
        meta.logoFile = "assets/takumicraft/TClogo.png";
        meta.url = "https://www.tntmodders.com";
        meta.authorList.add("Tom kate");
        meta.autogenerated = false;
    }
}