package com.tntmodders.project_404.core;

import com.tntmodders.project_404.TNT404Core;
import net.minecraftforge.fml.common.ModMetadata;

public class TNT404ModInfoCore {

    public static void load(ModMetadata meta) {
        meta.modId = TNT404Core.MODID;
        meta.name = TNT404Core.MODID;
        meta.description = "SCP-404-MC 'project_404' " +
                "アイテム番号: SCP-404-MC " +
                "オブジェクトクラス: Keter";
        meta.version = TNT404Core.VERSION;
        meta.credits = "このMODは http://www.scp-wiki.net/ の内容をもとに独自に二次創作した内容です。";
        meta.logoFile = "assets/project_404/logo.png";
        meta.url = "https://www.tntmodders.com";
        meta.authorList.add("Tom kate");
        meta.autogenerated = false;
    }
}